topics:
  -
    topic: /mobile_base/battery_state
    type: sensor_msgs/msg/BatteryState
  -
    topic: /mobile_base/cmd_audio
    type: irobot_create_msgs/msg/AudioNoteVector
  -
    topic: /mobile_base/cmd_lightring
    type: irobot_create_msgs/msg/LightringLeds
  -
    topic: /mobile_base/cmd_vel
    type: geometry_msgs/msg/Twist
  -
    topic: /mobile_base/dock
    type: irobot_create_msgs/msg/Dock
  -
    topic: /mobile_base/hazard_detection
    type: irobot_create_msgs/msg/HazardDetectionVector
  -
    topic: /mobile_base/imu
    type: sensor_msgs/msg/Imu
  -
    topic: /mobile_base/interface_buttons
    type: irobot_create_msgs/msg/InterfaceButtons
  -
    topic: /mobile_base/ir_intensity
    type: irobot_create_msgs/msg/IrIntensityVector
  -
    topic: /mobile_base/ir_opcode
    type: irobot_create_msgs/msg/IrOpcode
  -
    topic: /mobile_base/kidnap_status
    type: irobot_create_msgs/msg/KidnapStatus
  -
    topic: /mobile_base/mouse
    type: irobot_create_msgs/msg/Mouse
  -
    topic: /mobile_base/odom
    type: nav_msgs/msg/Odometry
  -
    topic: /mobile_base/rosout
    type: rcl_interfaces/msg/Log
  -
    topic: /mobile_base/slip_status
    type: irobot_create_msgs/msg/SlipStatus
  -
    topic: /mobile_base/stop_status
    type: irobot_create_msgs/msg/StopStatus
  -
    topic: /mobile_base/tf
    type: tf2_msgs/msg/TFMessage
  -
    topic: /mobile_base/tf_static
    type: tf2_msgs/msg/TFMessage
  -
    topic: /mobile_base/wheel_status
    type: irobot_create_msgs/msg/WheelStatus
  -
    topic: /mobile_base/wheel_ticks
    type: irobot_create_msgs/msg/WheelTicks
  -
    topic: /mobile_base/wheel_vels
    type: irobot_create_msgs/msg/WheelVels
